// data/packages.js
import parisImg from '../../assets/tripparis.jpg'
import dubaiImg from '../../assets/tripdubai.jpg'
import phuketImg from '../../assets/phuket.webp'
import baliImg from '../../assets/bali.webp'
import dubrovikImg from '../../assets/dubrovik.webp'
import gbreefImg from '../../assets/gbreef.webp'
import himachaImg from '../../assets/himachal.webp'
import delhiImg from '../../assets/delhi.webp'
import keralaImg from '../../assets/kerala.webp'
import philipinesImg from '../../assets/philippines.webp'
import abudhabiImg from '../../assets/abudhabi.webp'
import viennaImg from '../../assets/vienna.webp'
import veniceImg from '../../assets/venice.webp'
import riodeImg from '../../assets/riode.webp'
import swissalpsImg from '../../assets/swissalps.webp'
import santoriniImg from '../../assets/santorini.jpg'
import istanbulImg from '../../assets/istanbul.webp'
import newyorkImg from '../../assets/newyork.jpg'
import capetownImg from '../../assets/capetown.jpg'
import tokyoImg from '../../assets/tokyo.webp'
import amalfiImg from '../../assets/amalfi.webp'
import londonImg from '../../assets/london.webp'
import croatiaImg from '../../assets/croatiatrip.jpg'
import banfImg from '../../assets/banftrip.jpg'
import tripmacauImg from '../../assets/tripmacau.jpg'
import boraImg from '../../assets/tripbora.jpg'




const packagesData = [
  {
    id: 1,
    name: "Paris, France",
    location: "Île‑de‑France",
    category: "Heritage & Romance",
    img: parisImg,
    rating: 4.8,
    duration: "6 days / 5 nights",
    priceINR: 132000,
    desc: "Explore Eiffel Tower, Louvre, Montmartre, Seine Cruise.",
    stay: "4-star central Paris hotel",
    transport: "Airport transfer + daily metro pass",
  },
  {
    id: 2,
    name: "Dubai, UAE",
    location: "Dubai Emirate",
    category: "Luxury & Desert",
    img: dubaiImg,
    rating: 4.7,
    duration: "5 days / 4 nights",
    priceINR: 65000,
    desc: "Burj Khalifa, desert safari, dhow cruise, shopping.",
    stay: "4-star hotel with breakfast",
    transport: "Airport transfer + private AC minivan",
  },
  {
    id: 3,
    name: "Phuket, Thailand",
    location: "Andaman Sea",
    category: "Beach & Adventure",
    img: phuketImg,
    rating: 4.6,
    duration: "5 days / 4 nights",
    priceINR: 59000,
    desc: "Phi Phi tour, snorkeling, beach days & nightlife.",
    stay: "Beachside resort",
    transport: "Airport pickup + shared van transfers",
  },
  {
    id: 4,
    name: "Great Barrier Reef, Australia",
    location: "Queensland",
    category: "Marine & Nature",
    img: gbreefImg,
    rating: 4.5,
    duration: "7 days / 6 nights",
    priceINR: 106000,
    desc: "Snorkeling, reef cruise, marine wildlife spotting.",
    stay: "3-star reef motel near Cairns",
    transport: "Airport transfer + boat tours",
  },
  {
    id: 5,
    name: "London, UK",
    location: "England",
    category: "City & Culture",
    img: londonImg,
    rating: 4.7,
    duration: "5 days / 4 nights",
    priceINR: 123000,
    desc: "London Eye, museums, West End theatre, classic pubs.",
    stay: "3-4 star hotel near city center",
    transport: "Airport transfer + Oyster card",
  },
  {
    id: 6,
    name: "Machu Picchu, Peru",
    location: "Andes",
    category: "Heritage & Trekking",
    img: tripmacauImg,
    rating: 4.8,
    duration: "7 days / 6 nights",
    priceINR: 132500,
    desc: "Inca Trail, ruins, local markets, Andean scenery.",
    stay: "Hostels + mid-range Cusco hotel",
    transport: "Airport to hotel + train to Aguas Calientes",
  },
  {
    id: 7,
    name: "Banff National Park, Canada",
    location: "Alberta Rockies",
    category: "Mountain & Wildlife",
    img: banfImg,
    rating: 4.7,
    duration: "6 days / 5 nights",
    priceINR: 95000,
    desc: "Lake Louise, wildlife tours, gondola rides.",
    stay: "3-star lodge in Banff town",
    transport: "Airport transfer + shuttle services",
  },
  {
    id: 8,
    name: "Dubrovnik, Croatia",
    location: "Dalmatian Coast",
    category: "Coastal Heritage",
    img: dubrovikImg,
    rating: 4.7,
    duration: "5 days / 4 nights",
    priceINR: 88000,
    desc: "City walls walk, island hopping, Old Town tours.",
    stay: "Historic hotel inside city walls",
    transport: "Airport shuttle + local ferry",
  },
  {
    id: 9,
    name: "Bora Bora, French Polynesia",
    location: "South Pacific",
    category: "Tropical Luxury",
    img: boraImg,
    rating: 4.3,
    duration: "6 days / 5 nights",
    priceINR: 160000,
    desc: "Overwater bungalow, lagoon cruise, spa days.",
    stay: "4-star overwater bungalow",
    transport: "Airport transfer + boat shuttle",
  },
  {
    id: 10,
    name: "Amalfi Coast, Italy",
    location: "Campania",
    category: "Scenic Coastline",
    img: amalfiImg,
    rating: 4.7,
    duration: "6 days / 5 nights",
    priceINR: 125000,
    desc: "Cliffside villages, boat rides, lemon groves.",
    stay: "3-star seaside inn",
    transport: "Airport transfer + private boat",
  },
  {
    id: 11,
    name: "Tokyo & Kyoto, Japan",
    location: "Kanto & Kansai",
    category: "Modern & Cultural",
    img: tokyoImg,
    rating: 4.9,
    duration: "8 days / 7 nights",
    priceINR: 150000,
    desc: "Temples, bullet train, sushi, alt culture & tech.",
    stay: "3-4 star city hotels",
    transport: "JR Pass train travel + metro",
  },
  {
    id: 12,
    name: "Cape Town & Winelands, South Africa",
    location: "Western Cape",
    category: "Coastal & Wine",
    img: capetownImg,
    rating: 4.8,
    duration: "7 days / 6 nights",
    priceINR: 110000,
    desc: "Table Mountain, Robben Island, vineyard tour.",
    stay: "3-star city & vineyard lodges",
    transport: "Airport transfer + guided vehicle",
  },
  {
    id: 13,
    name: "Bali Adventure, Indonesia",
    location: "Bali",
    category: "Beach & Culture",
    img: baliImg,
    rating: 4.7,
    duration: "7 days / 6 nights",
    priceINR: 65000,
    desc: "Ubud jungle, beach clubs, temples & rice fields.",
    stay: "Resort & boutique villas",
    transport: "Airport pickup + private van",
  },
  {
    id: 14,
    name: "New York City, USA",
    location: "New York",
    category: "Iconic City",
    img: newyorkImg,
    rating: 4.8,
    duration: "6 days / 5 nights",
    priceINR: 145000,
    desc: "Statue of Liberty, Broadway, central park, museums.",
    stay: "3-4 star Manhattan hotel",
    transport: "Airport transfer + subway pass",
  },
  {
    id: 15,
    name: "Istanbul, Turkey",
    location: "Turkey",
    category: "History & Bazaar",
    img: istanbulImg,
    rating: 4.7,
    duration: "6 days / 5 nights",
    priceINR: 90000,
    desc: "Hagia Sophia, Bosphorus cruise, Grand Bazaar.",
    stay: "4-star hotel in Sultanahmet",
    transport: "Airport transfer + tram",
  },
  {
    id: 16,
    name: "Santorini, Greece",
    location: "Cyclades",
    category: "Romantic Escape",
    img: santoriniImg,
    rating: 4.8,
    duration: "5 days / 4 nights",
    priceINR: 100000,
    desc: "Blue-domed churches, sunset cruise, wineries.",
    stay: "Cliffside boutique hotel",
    transport: "Airport + ferry transfers",
  },
  {
    id: 17,
    name: "Rio de Janeiro, Brazil",
    location: "Rio",
    category: "Beach & Festivals",
    img: riodeImg,
    rating: 4.6,
    duration: "6 days / 5 nights",
    priceINR: 115000,
    desc: "Christ the Redeemer, Copacabana, samba nights.",
    stay: "3-star Copacabana hotel",
    transport: "Airport transfer + city van",
  },
  {
    id: 18,
    name: "Swiss Alps – Interlaken",
    location: "Switzerland",
    category: "Mountain & Adventure",
    img: swissalpsImg,
    rating: 4.9,
    duration: "6 days / 5 nights",
    priceINR: 155000,
    desc: "Jungfrau, hiking, paragliding, glacier visits.",
    stay: "4-star chalet hotel",
    transport: "Airport to Interlaken + trains",
  },
  {
    id: 19,
    name: "Venice & Florence, Italy",
    location: "Veneto & Tuscany",
    category: "Art & Romance",
    img: veniceImg,
    rating: 4.8,
    duration: "7 days / 6 nights",
    priceINR: 130000,
    desc: "Canals, Uffizi, Tuscan wine & countryside.",
    stay: "4-star city hotels",
    transport: "Train travel + walking tours",
  },
  {
    id: 20,
    name: "Vienna & Prague",
    location: "Austria & Czechia",
    category: "Culture & History",
    img: viennaImg,
    rating: 4.7,
    duration: "7 days / 6 nights",
    priceINR: 125000,
    desc: "Palaces, music, river cruises, castle walks.",
    stay: "3-4 star hotels",
    transport: "Train intercity travel",
  },
  {
    id: 21,
    name: "UAE Road Trip – Abu Dhabi & Dubai",
    location: "UAE",
    category: "Desert & City",
    img: abudhabiImg,
    rating: 4.8,
    duration: "6 days / 5 nights",
    priceINR: 68000,
    desc: "Sheikh Zayed Mosque, Ferrari World, Marina cruise.",
    stay: "4-star hotels",
    transport: "Private SUV with driver",
  },
  {
    id: 22,
    name: "Philippines – Manila & Palawan",
    location: "Philippines",
    category: "Beach & Island",
    img: philipinesImg,
    rating: 4.7,
    duration: "7 days / 6 nights",
    priceINR: 60000,
    desc: "Underground river, El Nido islands, local markets.",
    stay: "Resorts in Manila & beach cottages",
    transport: "Airport transfers + island boats",
  },
  {
    id: 23,
    name: "Kerala – Backwaters & Hill‑Stations",
    location: "India",
    category: "Nature & Culture",
    img: keralaImg,
    rating: 4.8,
    duration: "7 days / 6 nights",
    priceINR: 35000,
    desc: "Houseboat in Alleppey, tea estate in Munnar, Kathakali.",
    stay: "Homestay + hill resort + houseboat",
    transport: "AC car with driver",
  },
  {
    id: 24,
    name: "Golden Triangle – Delhi, Agra & Jaipur",
    location: "India",
    category: "Heritage",
    img: delhiImg,
    rating: 4.7,
    duration: "5 days / 4 nights",
    priceINR: 25000,
    desc: "Taj Mahal, Jaipur forts, Delhi heritage walk.",
    stay: "3-star hotels in each city",
    transport: "Private AC car",
  },
  {
    id: 25,
    name: "Himachal Manali & Rohtang",
    location: "India",
    category: "Mountain & Adventure",
    img: himachaImg,
    rating: 4.6,
    duration: "7 days / 6 nights",
    priceINR: 28000,
    desc: "Snow peaks, hot springs, Solang Valley, Rohtang Pass.",
    stay: "Hotel + valley campsite",
    transport: "Volvo to Manali + private vehicle",
  },
];

export default packagesData;
