import React, { useState } from "react";
import "./TermsModal.css";

const TermsModal = ({ onClose }) => {
  const [isChecked, setIsChecked] = useState(false);

  const handleAgree = () => {
    if (isChecked) {
      onClose();
    }
  };

  return (
    <div className="terms-overlay" onClick={onClose}>
      <div className="terms-modal" onClick={(e) => e.stopPropagation()}>
        <h2>Terms & Conditions</h2>

        <div className="terms-scroll">
          <h3>1. Electronic Record</h3>
          <p>
            This document constitutes an electronic record under the Information Technology Act, 2000 and associated rules, as amended. It is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <h3>2. Regulatory Compliance</h3>
          <p>
            Published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, this document outlines the Terms of Use, Privacy Policy, and platform access guidelines for https://kerithtravel.com and its associated mobile applications.
          </p>

          <h3>3. Platform Ownership</h3>
          <p>
            The platform is owned and operated by Kerith Travel and Tourism, a company registered under the Companies Act, 1956 with its head office in Kanyakumari, India.
          </p>

          <h3>4. Binding Agreement</h3>
          <p>
            By accessing or using our platform and services, you agree to be bound by these Terms of Use, which govern all interactions, transactions, and usage. These terms may be revised periodically, and it is your responsibility to stay informed of such changes.
          </p>

          <h3>5. User Definition</h3>
          <p>
            References to "you", "your", or "user" denote any individual or legal entity that has agreed to use the platform in accordance with these terms.
          </p>

          <h3>6. Acceptance of Terms</h3>
          <p>
            By browsing or transacting on our platform, you acknowledge and consent to all provisions set forth in these Terms of Use. Please read them carefully before proceeding.
          </p>

          <h3>7. Conditions of Use</h3>
          <ul>
            <li>You must provide accurate and complete information when registering or transacting.</li>
            <li>We do not guarantee the accuracy or completeness of platform content and disclaim any liability for errors therein.</li>
            <li>You use our services at your own risk and discretion.</li>
            <li>All platform content is proprietary and must not be reproduced or misused.</li>
            <li>Unauthorized usage may attract legal consequences.</li>
            <li>You are responsible for all fees or charges incurred while using the services.</li>
            <li>You agree not to engage in any unlawful or prohibited activities through our platform.</li>
            <li>External links provided are for convenience only; their usage is at your discretion and risk.</li>
            <li>Engaging our services constitutes a legally binding agreement with Kerith Travel and Tourism.</li>
          </ul>

          <h3>8. Indemnity</h3>
          <p>
            You agree to indemnify and hold harmless Kerith Travel and Tourism, its affiliates, and its representatives against any liabilities arising from your breach of these terms or violations of applicable laws.
          </p>

          <h3>9. Force Majeure</h3>
          <p>
            We shall not be held liable for delays or failures resulting from events beyond our reasonable control.
          </p>

          <h3>10. Jurisdiction</h3>
          <p>
            These terms are governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Kanyakumari, Tamil Nadu.
          </p>

          <h3>Privacy Policy</h3>
          <p>
            Kerith Travel and Tourism is committed to protecting your privacy and ensuring transparency in how we handle your personal information. This policy explains what data we collect, why we collect it, and how we use, store, and share it.
          </p>

          <h4>1. Data We Collect</h4>
          <ul>
            <li><strong>Personal Identifiable Information (PII):</strong> Name, contact details, address, and payment details.</li>
            <li><strong>Transaction Information:</strong> Booking history, payments, and invoices.</li>
            <li><strong>Device Information:</strong> IP address, browser type, OS, and access times.</li>
            <li><strong>Usage Data:</strong> Browsing patterns, clicks, and site navigation behavior.</li>
          </ul>

          <h4>2. Purpose of Data Collection</h4>
          <ul>
            <li>To process bookings and complete transactions securely.</li>
            <li>To provide customer service and support.</li>
            <li>To improve user experience and website performance.</li>
            <li>To comply with legal obligations (e.g., tax, accounting, AML regulations).</li>
            <li>To send marketing/promotional content (only with your explicit consent).</li>
          </ul>

          <h4>3. Data Sharing</h4>
          <p>
            We do not sell or rent your personal data. We may share your information with:
          </p>
          <ul>
            <li>Payment gateway partners for secure transactions.</li>
            <li>Government authorities when legally required.</li>
            <li>Third-party service providers bound by confidentiality agreements (e.g., hosting, analytics).</li>
          </ul>

          <h4>4. Data Security</h4>
          <ul>
            <li>SSL encryption for all data transmission.</li>
            <li>Restricted access to user data within our organization.</li>
            <li>Regular security audits and server hardening procedures.</li>
          </ul>

          <h4>5. Data Retention</h4>
          <p>
            We retain personal data only for as long as necessary to fulfill the purposes outlined above or as required by law.
          </p>

          <h4>6. User Rights</h4>
          <ul>
            <li>You can request access to your personal data.</li>
            <li>You have the right to correct or delete your data.</li>
            <li>You may object to data processing or request restriction.</li>
            <li>You can withdraw consent for marketing communications at any time.</li>
          </ul>

          <h4>7. Cookies</h4>
          <p>
            We use cookies and similar technologies to improve your browsing experience. You can manage cookie preferences via your browser settings.
          </p>

          <h4>8. Third-Party Links</h4>
          <p>
            Our platform may include links to third-party websites. We are not responsible for their privacy practices.
          </p>

          <h4>9. International Users</h4>
          <p>
            If you access our platform from outside India, you acknowledge that your data will be processed and stored in accordance with Indian data protection laws.
          </p>

          <h4>10. Contact</h4>
          <p>
            For any privacy-related questions or requests, please contact us at: <br />
            <strong>Email:</strong> support@kerithtravel.com <br />
            <strong>Address:</strong> Kerith Travel and Tourism, Kanyakumari, India
          </p>

          <h3>Refund & Cancellation Policy</h3>
          <ol>
            <li>Cancellations are accepted within 15 days of booking, subject to the terms of the travel service provider.</li>
            <li>No cancellations or refunds are allowed for last-minute or non-refundable bookings (e.g., flights, hotels, tour packages).</li>
            <li>Service-related issues (such as incorrect bookings or booking failures caused by us) must be reported within 15 days of the scheduled travel date.</li>
            <li>All warranty, service quality, or experience-related concerns should be addressed directly with the respective provider (e.g., airlines, hotels).</li>
            <li>Once approved, eligible refunds will be processed within 7 business days, subject to applicable cancellation fees and provider policies.</li>
          </ol>
        </div>

        <div className="terms-actions">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={isChecked}
              onChange={() => setIsChecked(!isChecked)}
            />
            I have thoroughly reviewed and agree to the Terms & Conditions and Privacy Policy.
          </label>
          <button className="agree-btn" disabled={!isChecked} onClick={handleAgree}>
            Agree & Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsModal;
