import React, { useState } from "react";
import "./TermsModal.css";

const TermsModal = ({ onClose }) => {
  const [isChecked, setIsChecked] = useState(false);

  const handleAgree = () => {
    if (isChecked) {
      onClose();
    }
  };

  return (
    <div className="terms-overlay" onClick={onClose}>
      <div className="terms-modal" onClick={(e) => e.stopPropagation()}>
        <h2>Terms & Conditions</h2>

        <div className="terms-scroll">
          <h3>1. Electronic Record</h3>
          <p>
            This document constitutes an electronic record under the Information Technology Act, 2000 and associated rules, as amended. It is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <h3>2. Regulatory Compliance</h3>
          <p>
            Published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, this document outlines the Terms of Use, Privacy Policy, and platform access guidelines for https://kerithtravel.com and its associated mobile applications.
          </p>

          <h3>3. Platform Ownership</h3>
          <p>
            The platform is owned and operated by Kerith Travel and Tourism, a company registered under the Companies Act, 1956 with its head office in Kanyakumari, India.
          </p>

          <h3>4. Binding Agreement</h3>
          <p>
            By accessing or using our platform and services, you agree to be bound by these Terms of Use, which govern all interactions, transactions, and usage. These terms may be revised periodically, and it is your responsibility to stay informed of such changes.
          </p>

          <h3>5. User Definition</h3>
          <p>
            References to "you", "your", or "user" denote any individual or legal entity that has agreed to use the platform in accordance with these terms.
          </p>

          <h3>6. Acceptance of Terms</h3>
          <p>
            By browsing or transacting on our platform, you acknowledge and consent to all provisions set forth in these Terms of Use. Please read them carefully before proceeding.
          </p>

          <h3>7. Conditions of Use</h3>
          <ul>
            <li>You must provide accurate and complete information when registering or transacting.</li>
            <li>We do not guarantee the accuracy or completeness of platform content and disclaim any liability for errors therein.</li>
            <li>You use our services at your own risk and discretion.</li>
            <li>All platform content is proprietary and must not be reproduced or misused.</li>
            <li>Unauthorized usage may attract legal consequences.</li>
            <li>You are responsible for all fees or charges incurred while using the services.</li>
            <li>You agree not to engage in any unlawful or prohibited activities through our platform.</li>
            <li>External links provided are for convenience only; their usage is at your discretion and risk.</li>
            <li>Engaging our services constitutes a legally binding agreement with Kerith Travel and Tourism.</li>
          </ul>

          <h3>8. Indemnity</h3>
          <p>
            You agree to indemnify and hold harmless Kerith Travel and Tourism, its affiliates, and its representatives against any liabilities arising from your breach of these terms or violations of applicable laws.
          </p>

          <h3>9. Force Majeure</h3>
          <p>
            We shall not be held liable for delays or failures resulting from events beyond our reasonable control.
          </p>

          <h3>10. Jurisdiction</h3>
          <p>
            These terms are governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Kanyakumari, Tamil Nadu.
          </p>

          <h3>Privacy Policy</h3>
          <p>
            We are committed to protecting your privacy. Please review our detailed Privacy Policy for information regarding data collection, usage, sharing, and your rights regarding your personal data.
          </p>

          <h3>Refund & Cancellation Policy</h3>
          <ol>
            <li>Cancellations are accepted within 15 days of purchase, subject to order status.</li>
            <li>No cancellations for perishable goods. Refunds only apply to quality-related complaints.</li>
            <li>Damaged or defective products must be reported within 15 days of delivery.</li>
            <li>Warranty-related issues should be addressed directly with the manufacturer.</li>
            <li>Approved refunds will be processed within 7 business days.</li>
          </ol>
        </div>

        <div className="terms-actions">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={isChecked}
              onChange={() => setIsChecked(!isChecked)}
            />
            I have thoroughly reviewed and agree to the Terms & Conditions.
          </label>
          <button className="agree-btn" disabled={!isChecked} onClick={handleAgree}>
            Agree & Close
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsModal;
